// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Audit trail code generator — produces hash-chained audit trail infrastructure
// code for the target project. The generated code provides:
//   - A persistent audit trail with configurable storage (file or memory)
//   - Hash-chained entries for tamper-evidence
//   - Chain verification functions
//   - Serialisation/deserialisation for the chosen storage backend

use anyhow::Result;

use crate::codegen::parser::ParsedManifest;

/// Generated audit trail module source code.
#[derive(Debug, Clone)]
pub struct GeneratedAudit {
    /// The complete source code for the audit module.
    pub module_code: String,
    /// The storage backend this was generated for ("file" or "memory").
    pub storage_backend: String,
    /// Whether hash-chaining is enabled.
    pub hash_chain_enabled: bool,
}

/// Generate the audit trail module source code based on the parsed manifest configuration.
/// This produces a complete, self-contained Rust module that can be included in the
/// target project to provide hash-chained audit trail functionality.
pub fn generate_audit_module(parsed: &ParsedManifest) -> Result<GeneratedAudit> {
    let storage_impl = match parsed.audit_storage.as_str() {
        "file" => generate_file_storage(parsed),
        "memory" => generate_memory_storage(parsed),
        other => anyhow::bail!("Unknown audit storage backend: {}", other),
    };

    let operation_names: Vec<String> = parsed
        .operations
        .iter()
        .map(|op| format!("\"{}\"", op.name))
        .collect();

    let module_code = format!(
        r#"// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by oblibeniser for project: {} v{}
// DO NOT EDIT — this file is auto-generated. Changes will be overwritten.
//
// Audit trail module — hash-chained, tamper-evident operation log.

use std::sync::Mutex;
use std::time::{{SystemTime, UNIX_EPOCH}};

/// Known operation names for this project (used for validation).
pub const KNOWN_OPERATIONS: &[&str] = &[{operation_list}];

/// Configuration for the audit trail, matching the manifest [audit] section.
pub struct AuditConfig {{
    pub hash_chain_enabled: bool,
    pub max_entries: usize,
    pub storage: &'static str,
}}

/// The project's audit configuration, derived from oblibeniser.toml.
pub const CONFIG: AuditConfig = AuditConfig {{
    hash_chain_enabled: {hash_chain},
    max_entries: {max_entries},
    storage: "{storage}",
}};

/// A single audit trail entry with hash-chain linkage.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AuditEntry {{
    /// Monotonically increasing sequence number.
    pub sequence: u64,
    /// Timestamp as Unix epoch milliseconds.
    pub timestamp_ms: u64,
    /// Name of the operation that was executed.
    pub operation_name: String,
    /// Hex-encoded hash of the serialised operation parameters.
    pub params_hash: String,
    /// Hex-encoded hash of the previous entry (empty for the first entry).
    pub prev_hash: String,
    /// Hex-encoded hash of this entry (computed from all fields above).
    pub entry_hash: String,
}}

impl AuditEntry {{
    /// Create a new entry, computing its hash from all fields plus the chain linkage.
    pub fn new(sequence: u64, operation_name: &str, params_hash: &str, prev_hash: &str) -> Self {{
        let timestamp_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let preimage = format!(
            "{{}}:{{}}:{{}}:{{}}:{{}}",
            sequence, timestamp_ms, operation_name, params_hash, prev_hash
        );
        let entry_hash = fnv1a_hash(&preimage);

        Self {{
            sequence,
            timestamp_ms,
            operation_name: operation_name.to_string(),
            params_hash: params_hash.to_string(),
            prev_hash: prev_hash.to_string(),
            entry_hash,
        }}
    }}

    /// Verify the integrity of this entry by recomputing its hash.
    pub fn verify(&self) -> bool {{
        let preimage = format!(
            "{{}}:{{}}:{{}}:{{}}:{{}}",
            self.sequence, self.timestamp_ms, self.operation_name, self.params_hash, self.prev_hash
        );
        fnv1a_hash(&preimage) == self.entry_hash
    }}
}}

/// The audit trail: a hash-chained, bounded sequence of entries.
pub struct AuditTrail {{
    entries: Vec<AuditEntry>,
}}

impl AuditTrail {{
    pub fn new() -> Self {{
        Self {{ entries: Vec::new() }}
    }}

    /// Record a new operation, linking it to the previous entry via hash chain.
    pub fn record(&mut self, operation_name: &str, params_hash: &str) -> &AuditEntry {{
        let sequence = self.entries.len() as u64;
        let prev_hash = if CONFIG.hash_chain_enabled {{
            self.entries.last().map(|e| e.entry_hash.clone()).unwrap_or_default()
        }} else {{
            String::new()
        }};

        let entry = AuditEntry::new(sequence, operation_name, params_hash, &prev_hash);
        self.entries.push(entry);

        // Enforce max_entries.
        if CONFIG.max_entries > 0 && self.entries.len() > CONFIG.max_entries {{
            let excess = self.entries.len() - CONFIG.max_entries;
            self.entries.drain(0..excess);
        }}

        self.entries.last().expect("TODO: handle error")
    }}

    /// Verify the integrity of the entire hash chain.
    /// Returns Ok(()) if intact, or Err with the index of the first broken link.
    pub fn verify_chain(&self) -> Result<(), usize> {{
        for (i, entry) in self.entries.iter().enumerate() {{
            if !entry.verify() {{
                return Err(i);
            }}
            if i > 0 && CONFIG.hash_chain_enabled {{
                if entry.prev_hash != self.entries[i - 1].entry_hash {{
                    return Err(i);
                }}
            }}
        }}
        Ok(())
    }}

    /// Return the number of entries.
    pub fn len(&self) -> usize {{ self.entries.len() }}

    /// Check if the trail is empty.
    pub fn is_empty(&self) -> bool {{ self.entries.is_empty() }}

    /// Get all entries (immutable slice).
    pub fn entries(&self) -> &[AuditEntry] {{ &self.entries }}

    /// Get the most recent entry.
    pub fn last(&self) -> Option<&AuditEntry> {{ self.entries.last() }}
}}

{storage_impl}

/// FNV-1a 64-bit hash, hex-encoded. Deterministic and fast for audit chain use.
/// For cryptographic tamper-evidence in production, replace with SHA-256.
fn fnv1a_hash(input: &str) -> String {{
    const FNV_OFFSET: u64 = 14695981039346656037;
    const FNV_PRIME: u64 = 1099511628211;
    let mut hash = FNV_OFFSET;
    for byte in input.as_bytes() {{
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(FNV_PRIME);
    }}
    format!("{{:016x}}", hash)
}}

// Global audit trail instance.
lazy_static::lazy_static! {{
    pub static ref GLOBAL_AUDIT: Mutex<AuditTrail> = Mutex::new(AuditTrail::new());
}}
"#,
        parsed.project_name,
        parsed.project_version,
        operation_list = operation_names.join(", "),
        hash_chain = parsed.hash_chain_enabled,
        max_entries = parsed.audit_max_entries,
        storage = parsed.audit_storage,
        storage_impl = storage_impl,
    );

    Ok(GeneratedAudit {
        module_code,
        storage_backend: parsed.audit_storage.clone(),
        hash_chain_enabled: parsed.hash_chain_enabled,
    })
}

/// Generate file-based storage implementation for persisting the audit trail to disk.
fn generate_file_storage(parsed: &ParsedManifest) -> String {
    format!(
        r#"/// File-based audit trail persistence.
/// Stores entries as newline-delimited JSON in a .oblibeniser-audit file.
pub mod storage {{
    use super::*;

    const AUDIT_FILE: &str = ".oblibeniser-audit/{project_name}.jsonl";

    /// Persist all current audit entries to disk.
    pub fn save(trail: &AuditTrail) -> std::io::Result<()> {{
        let path = std::path::Path::new(AUDIT_FILE);
        if let Some(parent) = path.parent() {{
            std::fs::create_dir_all(parent)?;
        }}
        let mut file = std::fs::File::create(path)?;
        for entry in trail.entries() {{
            let json = serde_json::to_string(entry)
                .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
            use std::io::Write;
            writeln!(file, "{{}}", json)?;
        }}
        Ok(())
    }}

    /// Load audit entries from disk.
    pub fn load() -> std::io::Result<Vec<AuditEntry>> {{
        let content = std::fs::read_to_string(AUDIT_FILE)?;
        let mut entries = Vec::new();
        for line in content.lines() {{
            if !line.trim().is_empty() {{
                let entry: AuditEntry = serde_json::from_str(line)
                    .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
                entries.push(entry);
            }}
        }}
        Ok(entries)
    }}
}}"#,
        project_name = parsed.project_name,
    )
}

/// Generate memory-only storage implementation (no persistence).
fn generate_memory_storage(_parsed: &ParsedManifest) -> String {
    r#"/// Memory-only audit trail storage (no persistence).
/// Entries exist only for the lifetime of the process.
pub mod storage {
    use super::*;

    /// No-op save for memory storage — entries are not persisted.
    pub fn save(_trail: &AuditTrail) -> std::io::Result<()> {
        Ok(())
    }

    /// No-op load for memory storage — always returns an empty trail.
    pub fn load() -> std::io::Result<Vec<AuditEntry>> {
        Ok(Vec::new())
    }
}"#
    .to_string()
}

/// Generate a standalone audit trail verification script that can be run
/// independently to check the integrity of a persisted audit trail.
pub fn generate_verification_script(parsed: &ParsedManifest) -> String {
    format!(
        r#"// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by oblibeniser for project: {} v{}
// Standalone audit trail verification script.
//
// Run: cargo run --bin verify-audit
//
// Loads the persisted audit trail and verifies the hash chain integrity.

fn main() {{
    println!("Verifying audit trail for project: {}...");

    match storage::load() {{
        Ok(entries) => {{
            println!("Loaded {{}} entries.", entries.len());
            let mut prev_hash = String::new();
            let mut broken = false;

            for (i, entry) in entries.iter().enumerate() {{
                if !entry.verify() {{
                    eprintln!("BROKEN: Entry {{}} has invalid self-hash!", i);
                    broken = true;
                }}
                if i > 0 && entry.prev_hash != prev_hash {{
                    eprintln!("BROKEN: Entry {{}} has invalid chain linkage!", i);
                    broken = true;
                }}
                prev_hash = entry.entry_hash.clone();
            }}

            if broken {{
                eprintln!("AUDIT TRAIL INTEGRITY CHECK FAILED.");
                std::process::exit(1);
            }} else {{
                println!("All {{}} entries verified. Chain is intact.", entries.len());
            }}
        }}
        Err(e) => {{
            eprintln!("Failed to load audit trail: {{}}", e);
            std::process::exit(1);
        }}
    }}
}}
"#,
        parsed.project_name, parsed.project_version, parsed.project_name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::parser;
    use crate::manifest;

    fn test_parsed() -> ParsedManifest {
        let toml = r#"
[project]
name = "audit-test"
version = "0.2.0"

[[operations]]
name = "create"
forward-fn = "store::create"
params = ["id:u64", "data:String"]
inverse-strategy = "mirror"

[audit]
hash-chain = true
storage = "file"
max-entries = 500

[undo]
max-depth = 20
"#;
        let m = manifest::parse_manifest(toml).expect("TODO: handle error");
        parser::parse_manifest(&m).expect("TODO: handle error")
    }

    #[test]
    fn test_generate_audit_module_file_storage() {
        let parsed = test_parsed();
        let audit = generate_audit_module(&parsed).expect("TODO: handle error");
        assert_eq!(audit.storage_backend, "file");
        assert!(audit.hash_chain_enabled);
        assert!(
            audit
                .module_code
                .contains("SPDX-License-Identifier: PMPL-1.0-or-later")
        );
        assert!(audit.module_code.contains("audit-test"));
        assert!(audit.module_code.contains("KNOWN_OPERATIONS"));
        assert!(audit.module_code.contains("\"create\""));
        assert!(audit.module_code.contains("max_entries: 500"));
        assert!(audit.module_code.contains("fn save"));
        assert!(audit.module_code.contains(".jsonl"));
    }

    #[test]
    fn test_generate_audit_module_memory_storage() {
        let toml = r#"
[project]
name = "mem-test"

[audit]
storage = "memory"
"#;
        let m = manifest::parse_manifest(toml).expect("TODO: handle error");
        let parsed = parser::parse_manifest(&m).expect("TODO: handle error");
        let audit = generate_audit_module(&parsed).expect("TODO: handle error");
        assert_eq!(audit.storage_backend, "memory");
        assert!(audit.module_code.contains("No-op save"));
    }

    #[test]
    fn test_generate_verification_script() {
        let parsed = test_parsed();
        let script = generate_verification_script(&parsed);
        assert!(script.contains("Verifying audit trail"));
        assert!(script.contains("audit-test"));
        assert!(script.contains("AUDIT TRAIL INTEGRITY CHECK FAILED"));
    }
}
