// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Inverse function generator — for each ReversibleOperation, generates the
// corresponding inverse function based on the chosen InverseStrategy:
//   - Mirror:     algebraic inverse (e.g., insert → delete, add → subtract)
//   - LogReplay:  mutation log recording + backward replay
//   - Snapshot:   full state capture + restore
//
// Output is Rust source code that integrates with the oblibeniser ABI types.

use anyhow::Result;

use crate::abi::{InverseStrategy, ReversibleOperation};
use crate::codegen::parser::ParsedManifest;

/// Generated inverse function code for a single operation.
#[derive(Debug, Clone)]
pub struct GeneratedInverse {
    /// Name of the generated inverse function.
    pub function_name: String,
    /// The original operation this inverse corresponds to.
    pub operation_name: String,
    /// Strategy used to generate this inverse.
    pub strategy: InverseStrategy,
    /// Generated Rust source code for the inverse function.
    pub code: String,
}

/// Generate inverse functions for all operations in the parsed manifest.
/// Returns a vector of GeneratedInverse structs containing the source code.
pub fn generate_inverses(parsed: &ParsedManifest) -> Result<Vec<GeneratedInverse>> {
    let mut results = Vec::new();
    for op in &parsed.operations {
        let generated = generate_single_inverse(op)?;
        results.push(generated);
    }
    Ok(results)
}

/// Generate the inverse function for a single operation, dispatching on strategy.
fn generate_single_inverse(op: &ReversibleOperation) -> Result<GeneratedInverse> {
    let code = match op.inverse_strategy {
        InverseStrategy::Mirror => generate_mirror_inverse(op),
        InverseStrategy::LogReplay => generate_log_replay_inverse(op),
        InverseStrategy::Snapshot => generate_snapshot_inverse(op),
    };

    Ok(GeneratedInverse {
        function_name: op.inverse_fn_name.clone(),
        operation_name: op.name.clone(),
        strategy: op.inverse_strategy.clone(),
        code,
    })
}

/// Generate a mirror (algebraic) inverse function.
/// The mirror inverse reverses the effect by applying the opposite transformation.
/// For example, if the forward function is `insert(key, value)`, the inverse is
/// `delete(key)` — it removes what was inserted.
fn generate_mirror_inverse(op: &ReversibleOperation) -> String {
    let param_list: Vec<String> = op
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.param_type))
        .collect();
    let param_names: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();

    format!(
        r#"/// Mirror inverse of `{forward_fn}`.
/// Algebraically reverses the forward operation by applying the opposite mutation.
/// Generated by oblibeniser — do not edit manually.
pub fn {inverse_fn}({params}) -> Result<InverseResult, OblibeniserError> {{
    // Record the current state of affected parameters for the audit trail.
    let _pre_state = capture_params_state(&[{param_refs}]);

    // Apply the mirror transformation:
    // The inverse of {forward_fn}({param_csv}) undoes the mutation.
    let result = {forward_fn}_mirror_undo({param_csv})?;

    // Log the inverse execution to the audit trail.
    AUDIT_TRAIL.lock().expect("TODO: handle error").record(
        "{inverse_fn}",
        &hash_params(&[{param_refs}]),
    );

    Ok(InverseResult {{
        operation: "{op_name}".to_string(),
        strategy: InverseStrategy::Mirror,
        success: true,
        detail: format!("Mirror inverse of {forward_fn} applied successfully"),
    }})
}}

/// Mirror undo implementation for {forward_fn}.
/// This function contains the actual reversal logic.
fn {forward_fn}_mirror_undo({params}) -> Result<(), OblibeniserError> {{
    // Reverse the mutation performed by {forward_fn}.
    // For mirror strategy, this applies the algebraic opposite.
    reverse_{op_name}({param_csv})?;
    Ok(())
}}"#,
        forward_fn = op.forward_fn,
        inverse_fn = op.inverse_fn_name,
        op_name = op.name,
        params = param_list.join(", "),
        param_csv = param_names.join(", "),
        param_refs = param_names
            .iter()
            .map(|n| format!("&{}", n))
            .collect::<Vec<_>>()
            .join(", "),
    )
}

/// Generate a log-replay inverse function.
/// The log-replay inverse records every mutation step in a log during the forward
/// operation, then replays that log in reverse order to undo.
fn generate_log_replay_inverse(op: &ReversibleOperation) -> String {
    let param_list: Vec<String> = op
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.param_type))
        .collect();
    let param_names: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();

    format!(
        r#"/// Log-replay inverse of `{forward_fn}`.
/// Replays the mutation log recorded during the forward operation in reverse order.
/// Generated by oblibeniser — do not edit manually.
pub fn {inverse_fn}({params}, mutation_log: &MutationLog) -> Result<InverseResult, OblibeniserError> {{
    // Replay the log entries in reverse chronological order.
    for entry in mutation_log.entries().rev() {{
        entry.undo()?;
    }}

    // Record the replay in the audit trail.
    AUDIT_TRAIL.lock().expect("TODO: handle error").record(
        "{inverse_fn}",
        &hash_params(&[{param_refs}]),
    );

    Ok(InverseResult {{
        operation: "{op_name}".to_string(),
        strategy: InverseStrategy::LogReplay,
        success: true,
        detail: format!(
            "Log-replay inverse of {forward_fn}: replayed {{}} entries",
            mutation_log.len()
        ),
    }})
}}

/// Forward wrapper for {forward_fn} that records mutations to a log.
/// Call this instead of {forward_fn} directly to enable log-replay undo.
pub fn {op_name}_logged({params}) -> Result<MutationLog, OblibeniserError> {{
    let mut log = MutationLog::new("{op_name}");

    // Execute {forward_fn} with mutation tracking enabled.
    {forward_fn}_with_log({param_csv}, &mut log)?;

    // Store the log for potential future undo.
    MUTATION_LOGS.lock().expect("TODO: handle error").insert(log.id(), log.clone());

    // Record in audit trail.
    AUDIT_TRAIL.lock().expect("TODO: handle error").record(
        "{op_name}",
        &hash_params(&[{param_refs}]),
    );

    Ok(log)
}}"#,
        forward_fn = op.forward_fn,
        inverse_fn = op.inverse_fn_name,
        op_name = op.name,
        params = param_list.join(", "),
        param_csv = param_names.join(", "),
        param_refs = param_names
            .iter()
            .map(|n| format!("&{}", n))
            .collect::<Vec<_>>()
            .join(", "),
    )
}

/// Generate a snapshot inverse function.
/// The snapshot inverse captures the entire state before the forward operation
/// and restores it on undo — the most expensive but most reliable strategy.
fn generate_snapshot_inverse(op: &ReversibleOperation) -> String {
    let param_list: Vec<String> = op
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.param_type))
        .collect();
    let param_names: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();

    format!(
        r#"/// Snapshot inverse of `{forward_fn}`.
/// Restores the full state captured before the forward operation was applied.
/// Generated by oblibeniser — do not edit manually.
pub fn {inverse_fn}(snapshot: &StateSnapshot) -> Result<InverseResult, OblibeniserError> {{
    // Restore state from the snapshot taken before {forward_fn} was called.
    restore_state(snapshot)?;

    // Record the restoration in the audit trail.
    AUDIT_TRAIL.lock().expect("TODO: handle error").record(
        "{inverse_fn}",
        &format!("snapshot_seq_{{}}", snapshot.at_sequence),
    );

    Ok(InverseResult {{
        operation: "{op_name}".to_string(),
        strategy: InverseStrategy::Snapshot,
        success: true,
        detail: format!(
            "Snapshot inverse of {forward_fn}: restored state from sequence {{}}",
            snapshot.at_sequence
        ),
    }})
}}

/// Forward wrapper for {forward_fn} that captures a state snapshot before execution.
/// Call this instead of {forward_fn} directly to enable snapshot-based undo.
pub fn {op_name}_with_snapshot({params}) -> Result<StateSnapshot, OblibeniserError> {{
    // Capture full state before the operation.
    let snapshot = capture_state()?;

    // Execute the forward operation.
    {forward_fn}({param_csv})?;

    // Record in audit trail.
    AUDIT_TRAIL.lock().expect("TODO: handle error").record(
        "{op_name}",
        &hash_params(&[{param_refs}]),
    );

    // Push onto the undo stack with the snapshot.
    UNDO_STACK.lock().expect("TODO: handle error").push(UndoEntry {{
        operation_name: "{op_name}".to_string(),
        forward_params: serialize_params(&[{param_refs}]),
        inverse_params: vec![],
        snapshot: Some(snapshot.clone()),
        audit_sequence: AUDIT_TRAIL.lock().expect("TODO: handle error").len() as u64 - 1,
    }});

    Ok(snapshot)
}}"#,
        forward_fn = op.forward_fn,
        inverse_fn = op.inverse_fn_name,
        op_name = op.name,
        params = param_list.join(", "),
        param_csv = param_names.join(", "),
        param_refs = param_names
            .iter()
            .map(|n| format!("&{}", n))
            .collect::<Vec<_>>()
            .join(", "),
    )
}

/// Generate the complete inverse module source file, including all inverses,
/// shared types, and the module-level boilerplate.
pub fn generate_inverse_module(parsed: &ParsedManifest) -> Result<String> {
    let inverses = generate_inverses(parsed)?;

    let mut output = String::new();

    // File header.
    output.push_str(&format!(
        r#"// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by oblibeniser for project: {} v{}
// DO NOT EDIT — this file is auto-generated. Changes will be overwritten.

use std::sync::Mutex;
use oblibeniser::abi::{{
    AuditTrail, InverseStrategy, StateSnapshot, UndoEntry, UndoStack,
}};

/// Result of executing an inverse operation.
#[derive(Debug, Clone)]
pub struct InverseResult {{
    pub operation: String,
    pub strategy: InverseStrategy,
    pub success: bool,
    pub detail: String,
}}

/// Error type for oblibeniser-generated inverse operations.
#[derive(Debug, thiserror::Error)]
pub enum OblibeniserError {{
    #[error("Inverse operation failed: {{0}}")]
    InverseFailed(String),
    #[error("State capture failed: {{0}}")]
    CaptureFailed(String),
    #[error("State restoration failed: {{0}}")]
    RestoreFailed(String),
    #[error("Mutation log replay failed: {{0}}")]
    ReplayFailed(String),
}}

/// Mutation log for log-replay strategy operations.
#[derive(Debug, Clone)]
pub struct MutationLog {{
    id: u64,
    operation: String,
    entries: Vec<MutationLogEntry>,
}}

/// A single entry in a mutation log, recording one atomic state change.
#[derive(Debug, Clone)]
pub struct MutationLogEntry {{
    pub field: String,
    pub old_value: Vec<u8>,
    pub new_value: Vec<u8>,
}}

impl MutationLog {{
    pub fn new(operation: &str) -> Self {{
        Self {{
            id: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos() as u64,
            operation: operation.to_string(),
            entries: Vec::new(),
        }}
    }}

    pub fn id(&self) -> u64 {{ self.id }}
    pub fn len(&self) -> usize {{ self.entries.len() }}
    pub fn is_empty(&self) -> bool {{ self.entries.is_empty() }}
    pub fn entries(&self) -> std::iter::Rev<std::slice::Iter<'_, MutationLogEntry>> {{
        self.entries.iter().rev()
    }}

    pub fn record(&mut self, field: &str, old_value: Vec<u8>, new_value: Vec<u8>) {{
        self.entries.push(MutationLogEntry {{
            field: field.to_string(),
            old_value,
            new_value,
        }});
    }}
}}

impl MutationLogEntry {{
    pub fn undo(&self) -> Result<(), OblibeniserError> {{
        // Application-specific: restore old_value to the field.
        // This is a placeholder — the actual implementation depends on the target.
        Ok(())
    }}
}}

// Global audit trail (thread-safe).
lazy_static::lazy_static! {{
    static ref AUDIT_TRAIL: Mutex<AuditTrail> = Mutex::new(
        AuditTrail::new({max_entries}, {hash_chain})
    );
    static ref UNDO_STACK: Mutex<UndoStack> = Mutex::new(
        UndoStack::new({max_depth}, {checkpoint_interval})
    );
    static ref MUTATION_LOGS: Mutex<std::collections::HashMap<u64, MutationLog>> =
        Mutex::new(std::collections::HashMap::new());
}}

/// Hash parameters for the audit trail (placeholder — use SHA-256 in production).
fn hash_params(params: &[&dyn std::fmt::Debug]) -> String {{
    let repr: Vec<String> = params.iter().map(|p| format!("{{:?}}", p)).collect();
    oblibeniser::abi::simple_hash(&repr.join(":"))
}}

/// Serialize parameters to bytes for the undo stack.
fn serialize_params(params: &[&dyn std::fmt::Debug]) -> Vec<u8> {{
    let repr: Vec<String> = params.iter().map(|p| format!("{{:?}}", p)).collect();
    repr.join(":").into_bytes()
}}

/// Capture the current state of specific parameters.
fn capture_params_state(params: &[&dyn std::fmt::Debug]) -> String {{
    let repr: Vec<String> = params.iter().map(|p| format!("{{:?}}", p)).collect();
    repr.join(":")
}}

/// Capture full application state (application-specific — implement per project).
fn capture_state() -> Result<StateSnapshot, OblibeniserError> {{
    Ok(StateSnapshot {{
        at_sequence: AUDIT_TRAIL.lock().expect("TODO: handle error").len() as u64,
        data: vec![],
    }})
}}

/// Restore full application state from a snapshot (application-specific).
fn restore_state(snapshot: &StateSnapshot) -> Result<(), OblibeniserError> {{
    // Application-specific state restoration.
    let _ = snapshot;
    Ok(())
}}

// ============================================================================
// Generated inverse functions
// ============================================================================

"#,
        parsed.project_name,
        parsed.project_version,
        max_entries = parsed.audit_max_entries,
        hash_chain = parsed.hash_chain_enabled,
        max_depth = parsed.undo_max_depth,
        checkpoint_interval = parsed.auto_checkpoint_interval,
    ));

    // Append each generated inverse function.
    for inverse in &inverses {
        output.push_str(&format!(
            "// --- Inverse for operation: {} (strategy: {}) ---\n\n",
            inverse.operation_name, inverse.strategy
        ));
        output.push_str(&inverse.code);
        output.push_str("\n\n");
    }

    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::parser;
    use crate::manifest;

    fn test_manifest() -> ParsedManifest {
        let toml = r#"
[project]
name = "test"
version = "0.1.0"

[[operations]]
name = "insert"
forward-fn = "db::insert"
params = ["key:String", "value:Vec<u8>"]
inverse-strategy = "mirror"

[[operations]]
name = "complex_update"
forward-fn = "db::complex_update"
params = ["id:u64", "data:String"]
inverse-strategy = "log-replay"

[[operations]]
name = "risky_migration"
forward-fn = "db::migrate"
params = ["version:u32"]
inverse-strategy = "snapshot"

[audit]
hash-chain = true
max-entries = 1000

[undo]
max-depth = 50
"#;
        let m = manifest::parse_manifest(toml).expect("TODO: handle error");
        parser::parse_manifest(&m).expect("TODO: handle error")
    }

    #[test]
    fn test_generate_inverses_count() {
        let parsed = test_manifest();
        let inverses = generate_inverses(&parsed).expect("TODO: handle error");
        assert_eq!(inverses.len(), 3);
    }

    #[test]
    fn test_mirror_inverse_contains_function() {
        let parsed = test_manifest();
        let inverses = generate_inverses(&parsed).expect("TODO: handle error");
        let mirror = &inverses[0];
        assert_eq!(mirror.function_name, "insert_inverse");
        assert!(mirror.code.contains("pub fn insert_inverse"));
        assert!(mirror.code.contains("Mirror"));
    }

    #[test]
    fn test_log_replay_inverse_contains_log() {
        let parsed = test_manifest();
        let inverses = generate_inverses(&parsed).expect("TODO: handle error");
        let replay = &inverses[1];
        assert_eq!(replay.strategy, InverseStrategy::LogReplay);
        assert!(replay.code.contains("mutation_log"));
        assert!(replay.code.contains("MutationLog"));
    }

    #[test]
    fn test_snapshot_inverse_contains_restore() {
        let parsed = test_manifest();
        let inverses = generate_inverses(&parsed).expect("TODO: handle error");
        let snapshot = &inverses[2];
        assert_eq!(snapshot.strategy, InverseStrategy::Snapshot);
        assert!(snapshot.code.contains("restore_state"));
        assert!(snapshot.code.contains("StateSnapshot"));
    }

    #[test]
    fn test_generate_inverse_module_complete() {
        let parsed = test_manifest();
        let module = generate_inverse_module(&parsed).expect("TODO: handle error");
        assert!(module.contains("SPDX-License-Identifier: PMPL-1.0-or-later"));
        assert!(module.contains("Generated by oblibeniser"));
        assert!(module.contains("pub fn insert_inverse"));
        assert!(module.contains("pub fn complex_update_inverse"));
        assert!(module.contains("pub fn risky_migration_inverse"));
    }
}
